In [ ]:
import pandas as pd

def hebing(data, lable_num_list):
    df = data.iloc[0:,lable_num_list]
    df['Col_sum'] = df.apply(lambda x: x.sum(), axis=1)
    data['hebing'] = df['Col_sum']


data_set = pd.read_csv("youziyuan.csv")
hebing(data_set,[12,14,16])
data_set.rename(index=str, columns={"hebing": "infantry_add_sumvalue"})
# hebing(data_set,[13,15,17])
# data_set.rename(index=str, columns={"hebing": "infantry_reduce_sumvalue"})
# hebing(data_set,[18,20,22])
# data_set.rename(index=str, columns={"hebing": "wound_infantry_add_sumvalue"})
# hebing(data_set,[19,21,23])
# data_set.rename(index=str, columns={"hebing": "wound_infantry_reduce_sumvalue"})
# data_set.drop(columns=data_set.columns[12:24])
print data_set.columns

In [21]:
import pandas as pd
data_set = pd.read_csv("youziyuan_0719.csv")
print len(data_set.columns)

87


In [45]:
import numpy as np
#计算相关性矩阵
data_set_demo1 = data_set.iloc[0:,range(2,6)+range(8,10)]
data_set_array1 = array(data_set_demo1)
print np.corrcoef(data_set_array1, rowvar=0)
data_set_demo2 = data_set.iloc[0:,range(12,18)]
data_set_array2 = array(data_set_demo2)
print np.corrcoef(data_set_array2, rowvar=0)
data_set_demo3 = data_set.iloc[0:,range(18,24)]
data_set_array3 = array(data_set_demo3)
print np.corrcoef(data_set_array3, rowvar=0)
data_set_demo4 = data_set.iloc[0:,range(28,34)]
data_set_array4 = array(data_set_demo4)
print np.corrcoef(data_set_array4, rowvar=0)
data_set_demo5 = data_set.iloc[0:,range(34,40)]
data_set_array5 = array(data_set_demo5)
print np.corrcoef(data_set_array5, rowvar=0)
data_set_demo6 = data_set.iloc[0:,range(44,50)]
data_set_array6 = array(data_set_demo6)
print np.corrcoef(data_set_array6, rowvar=0)
data_set_demo7 = data_set.iloc[0:,range(52,58)]
data_set_array7 = array(data_set_demo7)
print np.corrcoef(data_set_array7, rowvar=0)
data_set_demo8 = data_set.iloc[0:,range(62,68)]
data_set_array8 = array(data_set_demo8)
print np.corrcoef(data_set_array8, rowvar=0)
data_set_demo9 = data_set.iloc[0:,[75,76,78,79,80,82]]
data_set_array9 = array(data_set_demo9)
print np.corrcoef(data_set_array9, rowvar=0)
data_set_demo0 = data_set.iloc[0:,range(86,92)]
data_set_array0 = array(data_set_demo0)
print np.corrcoef(data_set_array0, rowvar=0)

[[1.         0.9645036  0.98564518 0.94840105 0.96569951 0.93606938]
 [0.9645036  1.         0.93662625 0.97031681 0.92451235 0.96760956]
 [0.98564518 0.93662625 1.         0.95957446 0.95089924 0.91291343]
 [0.94840105 0.97031681 0.95957446 1.         0.90705567 0.94836271]
 [0.96569951 0.92451235 0.95089924 0.90705567 1.         0.93380485]
 [0.93606938 0.96760956 0.91291343 0.94836271 0.93380485 1.        ]]
[[1.         0.89147267 0.72579059 0.67185397 0.17451307 0.16128518]
 [0.89147267 1.         0.70646216 0.80177102 0.17345124 0.19094118]
 [0.72579059 0.70646216 1.         0.8811064  0.20260567 0.18634435]
 [0.67185397 0.80177102 0.8811064  1.         0.19162429 0.21553866]
 [0.17451307 0.17345124 0.20260567 0.19162429 1.         0.99387338]
 [0.16128518 0.19094118 0.18634435 0.21553866 0.99387338 1.        ]]
[[1.         0.98161177 0.73003012 0.71190134 0.117826   0.10884042]
 [0.98161177 1.         0.69805583 0.71734775 0.11516358 0.11184871]
 [0.73003012 0.69805583 1.      

In [19]:
import numpy as np
for i in range(15):
    data_set_demo11 = data_set.iloc[0:,range(6*i+2,6*i+8)]
    data_set_array11 = np.array(data_set_demo11)
    print np.corrcoef(data_set_array11, rowvar=0)
    print data_set_demo11.columns
#print range(len(data_set.columns)//6)

[[1.         0.97095008 0.91839315 0.48869203 0.45034279 0.50435056]
 [0.97095008 1.         0.97008034 0.47534121 0.44872586 0.47167299]
 [0.91839315 0.97008034 1.         0.45820803 0.43846214 0.46165674]
 [0.48869203 0.47534121 0.45820803 1.         0.95516801 0.29835987]
 [0.45034279 0.44872586 0.43846214 0.95516801 1.         0.2635073 ]
 [0.50435056 0.47167299 0.46165674 0.29835987 0.2635073  1.        ]]
Index([u'wood_add_value', u'ivory_add_value', u'ivory_reduce_value',
       u'magic_add_value', u'magic_reduce_value', u'infantry_add_value'],
      dtype='object')
[[1.         0.70646216 0.80177102 0.17345124 0.9396284  0.73919974]
 [0.70646216 1.         0.8811064  0.20260567 0.62312784 0.8359659 ]
 [0.80177102 0.8811064  1.         0.19162429 0.6941589  0.93030836]
 [0.17345124 0.20260567 0.19162429 1.         0.13322178 0.18090111]
 [0.9396284  0.62312784 0.6941589  0.13322178 1.         0.73003012]
 [0.73919974 0.8359659  0.93030836 0.18090111 0.73003012 1.        ]]
Index

[[1.         0.00217942 0.00764638 0.00805981 0.12020822 0.06515172]
 [0.00217942 1.         0.47718563 0.54493474 0.13474916 0.27652008]
 [0.00764638 0.47718563 1.         0.77685273 0.14135006 0.36452403]
 [0.00805981 0.54493474 0.77685273 1.         0.19750351 0.44636409]
 [0.12020822 0.13474916 0.14135006 0.19750351 1.         0.73408852]
 [0.06515172 0.27652008 0.36452403 0.44636409 0.73408852 1.        ]]
Index([u'sr_rss_help_bonus_level', u'pvp_battle_count', u'pve_battle_count',
       u'avg_online_minutes', u'pay_price', u'pay_count'],
      dtype='object')


In [15]:
import numpy as np
data_set_demo11 = data_set.iloc[0:,range(10,16)]
data_set_array11 = np.array(data_set_demo11)
print np.corrcoef(data_set_array11, rowvar=0)
print data_set_demo11.columns

[[1.         0.19162429 0.6941589  0.93030836 0.15999609 0.40709577]
 [0.19162429 1.         0.13322178 0.18090111 0.99234252 0.17947738]
 [0.6941589  0.13322178 1.         0.73003012 0.117826   0.2809237 ]
 [0.93030836 0.18090111 0.73003012 1.         0.16500697 0.2893575 ]
 [0.15999609 0.99234252 0.117826   0.16500697 1.         0.10269428]
 [0.40709577 0.17947738 0.2809237  0.2893575  0.10269428 1.        ]]
Index([u'cavalry_reduce_value', u'shaman_add_value',
       u'wound_infantry_add_value', u'wound_cavalry_add_value',
       u'wound_shaman_add_value', u'general_acceleration_add_value'],
      dtype='object')


In [18]:
new_data_set = data_set.drop(columns=data_set.columns[[3,4,5,8,9,11]])
print new_data_set.columns
new_data_set.to_csv("youziyuan_0719.csv",index=None)

Index([u'user_id', u'register_time', u'wood_add_value', u'magic_reduce_value',
       u'infantry_add_value', u'cavalry_reduce_value',
       u'wound_infantry_add_value', u'wound_cavalry_add_value',
       u'wound_shaman_add_value', u'general_acceleration_add_value',
       u'building_acceleration_add_value', u'reaserch_acceleration_add_value',
       u'training_acceleration_add_value',
       u'training_acceleration_reduce_value',
       u'treatment_acceleraion_add_value',
       u'treatment_acceleration_reduce_value', u'bd_training_hut_level',
       u'bd_healing_lodge_level', u'bd_stronghold_level',
       u'bd_outpost_portal_level', u'bd_barrack_level',
       u'bd_healing_spring_level', u'bd_dolmen_level',
       u'bd_guest_cavern_level', u'bd_warehouse_level', u'bd_watchtower_level',
       u'bd_magic_coin_tree_level', u'bd_hall_of_war_level',
       u'bd_market_level', u'bd_hero_gacha_level', u'bd_hero_strengthen_level',
       u'bd_hero_pve_level', u'sr_scout_level', u'sr_traini

In [17]:
print data_set.columns[:20]
[3,4,5,8,9,11]

Index([u'user_id', u'register_time', u'wood_add_value', u'ivory_add_value',
       u'ivory_reduce_value', u'magic_add_value', u'magic_reduce_value',
       u'infantry_add_value', u'infantry_reduce_value', u'cavalry_add_value',
       u'cavalry_reduce_value', u'shaman_add_value',
       u'wound_infantry_add_value', u'wound_cavalry_add_value',
       u'wound_shaman_add_value', u'general_acceleration_add_value',
       u'building_acceleration_add_value', u'reaserch_acceleration_add_value',
       u'training_acceleration_add_value',
       u'training_acceleration_reduce_value'],
      dtype='object')
